/**
 * @file 루트 레이아웃 파일
 */
import type {Metadata} from 'next';
import '@/assets/css/reset.css';
import '@/assets/css/common.css';
import '@/assets/css/slide.css'
import '@/assets/css/main.css'
import '@/assets/css/qna.css'
import '@/assets/css/lib/swiper-bundle.min.css'
import MetaTags from '@/components/layout/meta-tags';
import Alert from '@/components/alert';
import Loading from '@/components/loading';
import LayoutSub from '@/app/layout-sub';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';

export const metadata: Metadata = {
  title: 'landline',
  description: 'Generated by create next app'
};

/**
 * 전역으로 반복되는 레이아웃과 전역 CSS를 설정하는 컴포넌트
 *
 * @param children
 * @constructor
 */
export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
    <MetaTags />
    <body>
    <Header />
    <LayoutSub>{children}</LayoutSub>
    <Footer />
    <Alert />
    <Loading />
    </body>
    </html>
  );
}
